spring:
  application:
    name: party-manager-main
  datasource:
    url: jdbc:mysql://localhost:3306/party-manager-services-test
    username: devuser
    password: Devdb_123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    
  flyway:
    url: jdbc:mysql://localhost:3306/party-manager-services-test
    user: devuser
    password: Devdb_123
    enabled: true
    
  jackson:
    property-naming-strategy: KEBAB_CASE
    
server:
  port: 8081